name: 'Validate NuPkg RocksDb'
description: 'Validates the NuGet package for RocksDb by ensuring all native libraries are correctly included and functional.' 

runs:
  using: "composite"
  steps:
    # Install packages needed for testing the native libraries.
    - name: Install packages
      shell: sh
      run: |
        if [ -f /etc/alpine-release ]; then
          apk add --no-cache bash icu
        fi

    - name: Install .NET SDKs
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x

    - name: Download NuGet package artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: nuget-package
        path: nupkgs

    - name: Run NupkgValidator
      shell: bash
      run: |
        cd NupkgValidator
        dotnet restore --source ../nupkgs
        dotnet build --no-restore
        dotnet run --no-build
