name: 'Build RocksDb'
description: 'Builds the native RocksDb libraries for all supported platforms using vcpkg and uploads them as artifacts for use in packaging the NuGet.' 

inputs:
  runtimeId:
    description: 'The runtime identifier (RID) to build for, e.g. linux-x64, win-x64, osx-arm64, etc.'
    required: true

runs:
  using: "composite"
  steps:
    # Install packages needed for building and testing the native libraries.
    - name: Install packages
      shell: sh
      run: |
        if [ -f /etc/alpine-release ]; then
          apk add --no-cache build-base cmake git ninja curl zip unzip tar bash icu pkgconf patchelf perl linux-headers
        fi

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: "afeb285c9e2e015292985856b9382ea1d82a4492"

    # Install .NET SDKs to extract the RocksDB version from the csproj file,
    # which is used to ensure the vcpkg version matches and to determine the expected library file names
    - name: Install .NET SDKs
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x

    - name: Check RocksDb version
      shell: bash
      run: |
        # Extract rocksdb version from csproj
        ROCKSDB_VERSION_CSPROJ="$(dotnet msbuild RocksDb.Net.Runtimes/ -getProperty:RocksDbVersion -nologo -v:q | tr -d '\r' | xargs)"
        echo "RocksDb version from csproj: $ROCKSDB_VERSION_CSPROJ"

        # Extract version from vcpkg.json
        ROCKSDB_VERSION_VCPKG=$(sed -n 's/.*"version": "\(.*\)".*/\1/p' vcpkg/ports/rocksdb/vcpkg.json)
        echo "RocksDb version from vcpkg.json: $ROCKSDB_VERSION_VCPKG"

        # Check if ROCKSDB_VERSION_VCPKG is the same as ROCKSDB_VERSION_CSPROJ
        if [[ "$ROCKSDB_VERSION_VCPKG" != "$ROCKSDB_VERSION_CSPROJ" ]]; then
          echo "RocksDb version mismatch! Tag version ($ROCKSDB_VERSION_VCPKG) does not match csproj version ($ROCKSDB_VERSION_CSPROJ)."
          exit 1
        fi

        ROCKSDB_VERSION=$ROCKSDB_VERSION_CSPROJ
        ROCKSDB_VERSION_MAJOR=$(echo "$ROCKSDB_VERSION" | cut -d. -f1)

        echo "ROCKSDB_VERSION=$ROCKSDB_VERSION" | tee -a $GITHUB_ENV
        echo "ROCKSDB_VERSION_MAJOR=$ROCKSDB_VERSION_MAJOR" | tee -a $GITHUB_ENV

    - name: Build RocksDb native libraries using vcpkg
      shell: bash
      env:
        VCPKG_FORCE_SYSTEM_BINARIES: ${{ contains(inputs.runtimeId, 'musl') && 1 || 0}}
      run: |
        vcpkg install rocksdb[snappy,zlib,lz4,zstd,bzip2] --triplet=${{ inputs.runtimeId }} --overlay-triplets=vcpkg-overlays/triplets

    - name: Copy native libraries to runtimes
      shell: bash
      run: |
        TARGET_DIR="RocksDb.Net.Runtimes/runtimes/${{ inputs.runtimeId }}/native"

        # Create the target directory for the native libraries in the runtimes folder
        mkdir -p "$TARGET_DIR"

        # Copy only MAJOR versioned shared library files for Linux and macOS.
        # Use cp -L to ensure we copy the actual files and not just the symlinks,

        # Copy shared libraries
        case "${{ inputs.runtimeId }}" in
          win*)
            # Copy .dll files for Windows
            cp -L vcpkg/installed/${{ inputs.runtimeId }}/bin/*.dll "$TARGET_DIR"

            # Rename rocksdb_shared.dll to librocksdb.MAJOR.dll
            mv "$TARGET_DIR/rocksdb-shared.dll" "$TARGET_DIR/librocksdb.$ROCKSDB_VERSION_MAJOR.dll"
            ;;

          linux*)
            # Copy MAJOR versioned .so files for Linux (e.g. librocksdb.so.11, libsnappy.so.1, libz.so.1).
            # Use cp -L to ensure we copy the actual files and not just the symlinks,
            find "vcpkg/installed/${{ inputs.runtimeId }}/lib" -maxdepth 1 -name "lib*.so.*" | grep -E '/lib[^.]+\.so\.[0-9]+$' | xargs -I {} cp -L {} "$TARGET_DIR"
            ;;

          osx*)
            # Copy MAJOR versioned .dylib files for macOS (e.g. librocksdb.11.dylib, libsnappy.1.dylib, libz.1.dylib).
            find "vcpkg/installed/${{ inputs.runtimeId }}/lib" -maxdepth 1 -name "*.dylib" | grep -E '/lib[^.]+\.[0-9]+\.dylib$' | xargs -I {} cp -L {} "$TARGET_DIR"
            ;;

          *)
            echo "Unsupported runtime ID: ${{ inputs.runtimeId }}"
            exit 1
            ;;
        esac

        # Show content of target directory
        ls -l "$TARGET_DIR"

        # Check if libraries are loadable
        case "${{ inputs.runtimeId }}" in
          win*)
            ;;

          linux*)
            # Check the copied .so files using ldd to ensure they have the expected version numbers in their names and correct dependencies
            ldd "$TARGET_DIR"/*.so* | tee "/tmp/ldd_output.log"
            if grep -q "not found" /tmp/ldd_output.log; then
              echo "Missing dependencies!"
              exit 1
            fi
            ;;

          osx*)
            # Check the copied dylib files using otool -L to ensure they have the expected version numbers in their names and correct dependencies
            for lib in "$TARGET_DIR"/*.dylib; do
            [ -e "$lib" ] || continue
              otool -L "$lib"
            done
            ;;
        esac

    - name: Upload native library artifact
      uses: actions/upload-artifact@v7
      with:
        name: runtimes-${{ inputs.runtimeId }}
        path: RocksDb.Net.Runtimes/runtimes
