name: 'Build RocksDb'
description: 'Builds the native RocksDb libraries for all supported platforms using vcpkg and uploads them as artifacts for use in packaging the NuGet.' 

inputs:
  vcpkgGitCommitId:
    description: 'The specific vcpkg git commit ID to use for the build. This ensures consistent builds by using a known state of vcpkg.'
    required: true
  vcpkgTriplet:
    description: 'The vcpkg triplet to use for building, e.g. x64-linux-dynamic-release, arm64-linux-dynamic-release, etc.'
    required: true
  runtimeId:
    description: 'The runtime identifier (RID) to build for, e.g. linux-x64, win-x64, osx-arm64, etc.'
    required: true
  libraryFiles:
    description: 'The expected library files to be produced by the build, used for validation and copying to the runtimes folder.'
    required: true

runs:
  using: "composite"
  steps:
    # Install Alpine packages needed for building and testing the native libraries.
    # Note: icu is needed for dotnet
    - name: Install Alpine packages
      if: contains(inputs.runtimeId, 'linux-musl')
      shell: sh
      run: |
        apk add --no-cache build-base cmake git ninja curl zip unzip tar bash icu pkgconf patchelf perl linux-headers

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: "${{ inputs.vcpkgGitCommitId }}"

    # Install .NET SDKs to extract the RocksDB version from the csproj file,
    # which is used to ensure the vcpkg version matches and to determine the expected library file names
    - name: Install .NET SDKs
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x

    - name: Check RocksDb version
      shell: bash
      run: |
        # Extract rocksdb version from csproj
        ROCKSDB_VERSION_CSPROJ="$(dotnet msbuild RocksDb.Net.Runtimes/ -getProperty:RocksDbVersion -nologo -v:q | tr -d '\r' | xargs)"
        echo "Version from csproj: $ROCKSDB_VERSION_CSPROJ"

        # Extract version from vcpkg.json
        ROCKSDB_VERSION_VCPKG=$(sed -n 's/.*"version": "\(.*\)".*/\1/p' vcpkg/ports/rocksdb/vcpkg.json)
        echo "Version from vcpkg.json: $ROCKSDB_VERSION_VCPKG"

        # Check if ROCKSDB_VERSION_VCPKG is the same as ROCKSDB_VERSION_CSPROJ
        if [[ "$ROCKSDB_VERSION_VCPKG" != "$ROCKSDB_VERSION_CSPROJ" ]]; then
          echo "Version mismatch! Tag version ($ROCKSDB_VERSION_VCPKG) does not match csproj version ($ROCKSDB_VERSION_CSPROJ)."
          exit 1
        fi

        echo "ROCKSDB_VERSION=$ROCKSDB_VERSION_CSPROJ" >> $GITHUB_ENV
        echo "ROCKSDB_VERSION_MAJOR=${ROCKSDB_VERSION_CSPROJ%%.*}" >> $GITHUB_ENV

        echo "ROCKSDB_VERSION=$ROCKSDB_VERSION_CSPROJ"
        echo "ROCKSDB_VERSION_MAJOR=${ROCKSDB_VERSION_CSPROJ%%.*}"

    - name: Build rocksdb
      shell: bash
      env:
        VCPKG_FORCE_SYSTEM_BINARIES: ${{ contains(inputs.runtimeId, 'musl') || 0}}
      run: |
        vcpkg install rocksdb[snappy,zlib] --triplet=${{ inputs.vcpkgTriplet }} --overlay-triplets=vcpkg-overlays/triplets
        find vcpkg/installed/${{ inputs.vcpkgTriplet }}

    - name: Copy to runtimes
      shell: bash
      run: |
        mkdir -p RocksDb.Net.Runtimes/runtimes/${{ inputs.runtimeId }}/native
        cp -L vcpkg/installed/${{ inputs.vcpkgTriplet }}/${{ inputs.libraryFiles }} RocksDb.Net.Runtimes/runtimes/${{ inputs.runtimeId }}/native/

    - name: Post-process Linux native binaries
      if: runner.os == 'Linux'
      shell: bash
      run: |
        # Patch librocksdb.so to have an RPATH of $ORIGIN, which allows it to find its dependencies in the same folder
        # without needing absolute paths. This is crucial for Linux where the dynamic linker
        # does not search the executable directory by default.
        patchelf --set-rpath '$ORIGIN' "RocksDb.Net.Runtimes/runtimes/${{ inputs.runtimeId }}/native/librocksdb.so.$ROCKSDB_VERSION_MAJOR"

        # Check for missing dependencies using ldd. If any "not found" entries are present, fail the build.
        ldd RocksDb.Net.Runtimes/runtimes/${{ inputs.runtimeId }}/native/* | tee ldd_output.txt
        if grep -q "not found" ldd_output.txt; then
          echo "Error: Missing dependencies detected in Linux binaries!"
          exit 1
        fi

    - name: Post-process macOS native binaries
      if: runner.os == 'macOS'
      shell: bash
      run: |
        TARGET_DIR="RocksDb.Net.Runtimes/runtimes/${{ inputs.runtimeId }}/native"
        TARGET_LIB_FILE_NAME="librocksdb.$ROCKSDB_VERSION_MAJOR.dylib"
        TARGET_LIB="$TARGET_DIR/$TARGET_LIB_FILE_NAME"

        # Dynamically find and fix Snappy dependency. Search for 'libsnappy.1.' followed by versioning
        OLD_SNAPPY=$(otool -L "$TARGET_LIB" | grep -o "@rpath/libsnappy\.1\.[0-9.]*dylib" | head -n 1)
        if [ ! -z "$OLD_SNAPPY" ]; then
          install_name_tool -change "$OLD_SNAPPY" "@loader_path/libsnappy.1.dylib" "$TARGET_LIB"
        fi

        # Dynamically find and fix Zlib dependency. Search for 'libz.1.' followed by versioning
        OLD_ZLIB=$(otool -L "$TARGET_LIB" | grep -E -o "@rpath/libz\.1\.[0-9.]*dylib" | head -n 1)
        if [ ! -z "$OLD_ZLIB" ]; then
          install_name_tool -change "$OLD_ZLIB" "@loader_path/libz.1.dylib" "$TARGET_LIB"
        fi

        # Standardize internal IDs (Self-Identity)
        # This ensures the files identify as the names we expect

        install_name_tool -id "@rpath/$TARGET_LIB_FILE_NAME" "$TARGET_LIB"
        install_name_tool -id "@rpath/libsnappy.1.dylib" "$TARGET_DIR/libsnappy.1.dylib"
        install_name_tool -id "@rpath/libz.1.dylib" "$TARGET_DIR/libz.1.dylib"

        for lib in $TARGET_DIR/*; do
          otool -L "$lib"
        done

    - name: Upload native library artifact
      uses: actions/upload-artifact@v7
      with:
        name: runtimes-${{ inputs.runtimeId }}
        path: RocksDb.Net.Runtimes/runtimes
