name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build RocksDb native libraries for all platforms in parallel. (non-musl)
  build-rocksdb:
    strategy:
      fail-fast: false
      matrix: &platform-matrix
        runtimeId: [win-x64, win-arm64, linux-x64, linux-arm64, osx-x64, osx-arm64]
        include:
          - runtimeId: win-x64
            os: windows-latest

          - runtimeId: win-arm64
            os: windows-11-arm

          - runtimeId: linux-x64
            os: ubuntu-latest

          - runtimeId: linux-arm64
            os: ubuntu-24.04-arm

          - runtimeId: osx-x64
            os: macos-latest

          - runtimeId: osx-arm64
            os: macos-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/buildRocksDb
        with:
          runtimeId: ${{ matrix.runtimeId }}

  # Build RocksDb native libraries for musl-based Linux platforms in parallel
  # Musl-based Linux platforms require a container with Alpine, so we build them in a separate job using an Alpine container
  build-rocksdb-musl:
    strategy:
      fail-fast: false
      matrix: &platform-matrix-musl
        runtimeId: [linux-musl-x64, linux-musl-arm64]
        include:
          - runtimeId: linux-musl-x64
            os: ubuntu-latest

          - runtimeId: linux-musl-arm64
            os: ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}
    container: alpine:latest
    steps:
      # action/checkout fails on Alpine Arm64 without this fix
      - name: Fix Alpine arm64 compatibility
        if: matrix.runtimeId == 'linux-musl-arm64'
        uses: laverdet/alpine-arm64@v1

      - uses: actions/checkout@v6

      - uses: ./.github/actions/buildRocksDb
        with:
          runtimeId: ${{ matrix.runtimeId }}

  # Build NuGet package after all native libraries have been built successfully
  build-nupkg:
    needs: [build-rocksdb, build-rocksdb-musl]
    runs-on: ubuntu-latest
    if: always() && needs.build-rocksdb.result == 'success' && needs.build-rocksdb-musl.result == 'success'
    steps:
      - uses: actions/checkout@v6

      - name: Install .NET SDKs
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            10.0.x

      - name: Download all native library artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: runtimes-*
          path: RocksDb.Net.Runtimes/runtimes
          merge-multiple: true

      - name: Pack NuGet package
        shell: bash
        run: |
          dotnet pack -c Release -o nupkgs

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v7
        with:
          name: nuget-package
          path: nupkgs/*.nupkg

  # Validate the NuGet package by running tests that load the native libraries and perform basic operations to ensure they are working correctly. (non-musl)
  validate-nupkg:
    needs: [build-nupkg]
    if: always() && needs.build-nupkg.result == 'success'
    strategy:
      fail-fast: false
      matrix: *platform-matrix

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/validateNupkg

  # Validate the NuGet package by running tests that load the native libraries and perform basic operations to ensure they are working correctly. (musl)
  validate-nupkg-musl:
    needs: [build-nupkg]
    if: always() && needs.build-nupkg.result == 'success'
    strategy:
      fail-fast: false
      matrix: *platform-matrix-musl

    runs-on: ${{ matrix.os }}
    container: alpine:latest
    steps:
      # action/checkout fails on Alpine Arm64 without this fix
      - name: Fix Alpine arm64 compatibility
        if: matrix.runtimeId == 'linux-musl-arm64'
        uses: laverdet/alpine-arm64@v1

      - uses: actions/checkout@v6

      - uses: ./.github/actions/validateNupkg
